# 异常

## 一、什么是异常

异常：程序执行过程中的不正常情况。

以下程序执行过程中发生了不正常的情况，二这种不正常的情况叫做：异常。

```java
int a = 10;
int b = 0;
int c = a / b;
// Exception in thread "main" java.lang.ArithmeticException: / by zero
```

## 二、异常机制有什么用

作用：增强程序的健壮性。

Java 语言是很完善的语言，提供了异常的处理方式，以上程序执行过程中出现了不正常情况Java 把该异常信息打印输出到控制台，供程序员参考。程序员看到异常信息之后，可以对程序进行修改，让程序更加的健壮。

## 三、异常的存在形式

异常在 Java 中以类的形式存在，每个异常都可以创建对象。

```java
// 通过“异常类”实例化“异常对”
NumberFormatException nfe = new NumberFormatException("数字格式化异常!");
System.out.printIn(nfe);
// java.lang.NumberFormatException: 数字格式化异常!
```

再看以下代码：

```java
int a = 10;
int b = 0;
int c = a / b;  // 实际 JVM 在执行到此处的时候，就会 new 异常对象：new ArithmeticException("/ by zero")
// 并且 JVM 将 new 的异常对象抛出，打印输出信息到控制台了
```

异常对应的现实生活中是怎样的?

火灾(异常类):

+ 2008年8月8日，小明家着火了(异常对象)
+ 2008年8月9日，小刚家着火了(异常对象)
+ 2008年9月8日，小红家着火了(异常对象)

## 四、异常的继承结构

+ Object
  + Throwable（可抛出的）
    + Error（不可处理，直接退出 JVM）
    + Exception（可处理的）
      + 直接子类：编译时异常
        要求程序员在编写程序阶段必须预先处理。
      + RuntimeException：运行时异常

![image-20230905201502624](https://gitee.com/LowProfile666/image-bed/raw/master/img/202309052015717.png)

 编译时异常和运行时异常，都是发生在运行阶段，编译阶段异常是不会发生的。

所有的异常都是在运行阶段发生的，因为只有运行解读那才可以 new 对象。

## 五、编译时异常和运行时异常的区别

编译时异常一般发生的概率比较高。

运行时异常一般发生的概率比较低。

编译时异常又被称为受检异常（Checked Exception）、受控异常；运行时异常又被称为未受检异常（Unchecked Exception）、未受控异常。

## 六、处理异常

方法一：在方法声明的位置上，使用 `throws `关键字，抛给上一级（谁调用就抛给谁）。

方法二：使用 `try catch` 语句进行异常的捕捉。

举个例子：

我是某集团的一个销售员，因为我的失误，导致公司损失了1000元（异常发生了）。我有两种处理方式，

+ 第一种方式:我把这件事告诉我的领导【异常上抛】
+ 第二种方式:我自己掏腰包把这个钱补上。【异常的捕捉】

注意：Java 中异常发生之后，如果一直上抛，最终抛给了 main 方法，main 方法继续上抛给了 JVM，那么最终该程序会被终止。

```java
public class Main{
	public static void main(String[] args) {
        /*
        程序执行到此处发生了ArithmeticException异常,
        底层new了一个ArithmeticException异常对象然后抛出了，
        由于是main方法调用了100 / 0，
        所以这个异常ArithmeticException抛给了main方法，
        main方法没有处理，将这个异常自动抛给了JVM，
        JVM最终终止程序的执行

        ArithmettcException 继承 RuntimeException，属于运行时异常，
        在编写程序阶段不需要对这种异常进行预先的处理。
        */
		System.out.println(100 / 0);
		System.out.println("HelloWorld");

	}
}
```

以下代码会报错：

```java
public class Main{
	public static void main(String[] args){
		doSome();
	}
	public static void doSome() throws ClassNotFoundException {
	System.out.println("doSome");
	}
}
```

doSome方法在方法声明的位置上使用了:throws ClassNotFoundException这个代码，表示doSome()方法在执行过程中，有可能会出现CLassNotFoundException异常，叫做类没找到异常。这个异常直接父类是:Exception，所以CLassNotFoundException属于编译时异常。

main方法中调用doSome()方法，因为doSome()方法声明位置上有:throws ClassNotFoundException，我们在调用doSome()方法的时候必须对这种异常进行预先的处理。如果不外理，编译器就报错。
编译器报错信息: Unhandled exception: java.lang.ClassNotFoundException

 所以在 main 方法中必须处理异常：

方法一：在方法的声明位置继续使用 throws，继续上抛异常。

```java
public class Main{
	public static void main(String[] args) throws ClassNotFoundException {
		doSome();
	}
	public static void doSome() throws ClassNotFoundException {		System.out.println("doSome");
	}
}
```

方法二：使用 `try catch` 进行捕捉：

```java
public class Main{
	public static void main(String[] args){
        try{
            doSome();
        } catch (ClassNotFoundException e){
        	   e.printStackTrace();
        }
	}
	public static void doSome() throws ClassNotFoundException {		System.out.println("doSome");
	}
}
```

### throws

`throws` 后面可以跟多个异常，多个异常之间用逗号隔开。

```java
public void m() throws IOException, ClassNotFoundException{
    // ....
}
```

一般不建议在 main 方法上使用 throws，因为这个异常如果真的发生了，一定会抛给 JVM，程序就一定会被终止。

### try catch

语法格式：

```java
try {
    // try 尝试
}  catch(Exception e) {
    // catch 捕捉
    // 这里是捕捉异常后走的分支
}
```

`catch` 后面的像是一个形式参数。这个分治中可以使用 `e` 引用，`e` 保存的内存地址是那个 new 出来的异常对象的内存地址。

**深入**

+ `catch` 后面的小括号中的类型可以是具体的异常类型，也可以是该异常类型的父类型。

+ `catch` 可以写多个，建议 `catch` 的时候，精确的一个一个处理，这样有利于程序的调试。

+ `catch` 写多个的时候，异常类型从上到下必须遵守从小到大原则。

+ `catch` 后面可以使用 `|` 符号捕捉多个异常。这是 JDK 8 的新特性。

  ```java
  try {
      doSome();
  } catch (IOException | FileNotFoundException e) {
      System.out.println("多个异常类型可以都可以被捕捉");
  }
  ```

### finally

在 `finally` 子句中的代码是最后执行的，并且是一定会执行的，即使 `try `语句块中出现了异常。

`finally` 子句必须和 `try` 一起出现，不能单独编写。

使用场景：

通常在 `finally` 子句中完成资源的关闭/释放。

```java
try {
    // 创建输入流对象
    FileInputStream fis = new FileInputStream(fileLoaction);
    
    String s = null;
    s.toString();  // 这里一定抛出异常
    
    // 关闭输入流对象，不关闭会占用资源
    fis.close();
} catch(FileNotFoundException e) {
    e.printStackTrace();
} catch(IOException e) {
    e.printStackTrace();
} catch(NullPointerException e) {
    e.printStackTrace();
}
```

在以上代码中，流使用完应该被关闭，即使程序出现了异常也应该被关闭。而在以上代码中，如果出现异常了，关闭流的代码就执行不到，所以可以使用 `finally` 子句确保关闭流的操作一定被执行：

```java
FileInputStream fis;
try {
    // 创建输入流对象
    fis = new FileInputStream(fileLoaction);
    
    String s = null;
    s.toString();  // 这里一定抛出异常
    
    // 关闭输入流对象，不关闭会占用资源
    fis.close();
} catch(FileNotFoundException e) {
    e.printStackTrace();
} catch(IOException e) {
    e.printStackTrace();
} catch(NullPointerException e) {
    e.printStackTrace();
} finally {
    if (fis != null)  // 避免空指针异常
	    try {
            fis.close();  // 会抛出异常
        } catch (IOException e) {
            e.printStackTrace();
        }
}
```

**可以不用 catch 子句**

只有 `try` 和 `finally` ，没有 `catch` 是可以的。`try` 不能单独使用。

```java
try {
    System.out.println("try。。");
    return;
} finally {
	 System.out.println("finally。。");
}
// 这里不能写代码，因为这个代码执行不到
```

以上代码执行顺序：

+ 先执行 try。。
+ 再执行 finally。。
+ 最后执行 return（return 语句只要执行方法必然结束）

以下情况的 `finally` 不会被执行：

```java
try {
    System.out.println("try。。");
    System.exit(0);  // 退出 JVM
} finally {
	 System.out.println("finally。。");
}
```

退出 JVM 后，`finally` 子句就不会被执行了。

**finally 的一个面试题**

```java
public class Main{
	public static void main(String[] args){
		System.out.println(m());  // 100
	}
	public static int m() {
		int i = 100;
		try {
			return n;
		} finally {
			n++;
		}
	}
}
```

以上代码输出结果是 100。

规则：

+ 方法体中的代码必须遵循自上而下的顺序依次执行
+ return 语句一旦执行，整个帆帆必须结束

`retrun i` 这句代码出现在 `i = 100` 的下面，所以最终结果必须是返回 100；`return` 语句还必须保证是最后执行的，一旦执行，整个方法结束。

将以上程序反编译后如下，可以看到执行过程：

```jade
import java.io.PrintStream;

public class Main
{

    public Main()
    {
    }

    public static void main(String args[])
    {
        System.out.println(m());
    }

    public static int m()
    {
        int i = 100;
        int j = i;
        i++;
        return j;
        Exception exception;
        exception;
        i++;
        throw exception;
    }
}
```

最主要的是这一段：

```java
int i = 100;
int j = i;
i++;
return j;
```

这段代码表示了该程序是怎么执行的，也满足了上面的两条规则。

### final、finally、finalize区别

+ `final` 是一个关键字，表示最终的、不变的。
  + 修饰的类无法继承
  + 修饰的方法无法覆盖
  + 修饰的变量无法重新赋值
+ `finally` 也是一个关键字，和 `try` 联合使用，使用在异常处理机制中。
  + 该语句块中的代码是必须执行的
+ `finalize()` 是 `Object` 类中的一个方法，所以 `finalize` 是方法名，是一个标识符。
  + 这个方法由垃圾回收机制调用

### 代码执行顺序

在异常发生后，如果没有被捕捉，发生异常的代码行后面的代码是不会执行的。

```java
public void m() throws Exception{
    doSome();  
    System.out.println("上面的方法抛出了异常，这里的代码不会被执行");
}
```

使用 `try catch` 捕捉异常后，在 `try` 语句块中，异常发生的代码行后面的代码也不会执行，会直接进入对应的 `catch` 语句。

```java
public void m() throws Exception{
    try {
        doSome();  
    	System.out.println("上面的方法抛出了异常，这里的代码不会被执行");
    } catch (Exception e) {
        System.out.println("这里会被执行");
        e.printStackTrace();
    }
    System.out.println("这里的代码会继续执行");
}
```

### 怎么选择

异常应该捕捉还是上抛？

如果希望调用者来处理，则选择 throws 上抛。其他i情况都是用捕捉的方式。

## 七、异常对象的常用方法

异常对象有两个非常重要的方法：

+ 获取异常简单的描述信息
  ```java
  exception.getMessage();
  ```

+ 打印异常追踪的堆栈信息
  ```java
  exception.printStackTrace();
  ```

```java
public class Main{
	public static void main(String[] args){
		NullPointerException e = new NullPointerException("空指针异常哈哈哈");
        
		// 这个信息实际上就是上面构造方法的参数
		System.out.println(e.getMessage());  // 空指针异常哈哈哈

		e.printStackTrace();
        /*
        java.lang.NullPointerException: 空指针异常哈哈哈
			at Main.main(Main.java:8)
        */

		System.out.println("hello");  // hello
	}
```

怎么看异常追踪信息？从上往下一行一行看

```java
public class Main{
	public static void main(String[] args){
		dfs(5);
	}
	public static int dfs(int n) {
		if (n == 0)
			return 0;
		return dfs(n-1) / (n-1);
	}
}
```

以上代码会报异常：

```
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at Main.dfs(Main.java:8)
	at Main.dfs(Main.java:8)
	at Main.dfs(Main.java:8)
	at Main.dfs(Main.java:8)
	at Main.dfs(Main.java:8)
	at Main.main(Main.java:3)
```

从上往下看，第一行表示异常类型及信息，第二行表示异常发生的位置，第三行表示调用第二行抛出异常的方法的位置，依次类推，最后一行表示主方法调用该方法的位置。

## 八、自定义异常

第一步：编写一个类继承 Exception 或者 RuntimeException。

第二步：提供两个构造方法，一个无参数的，一个带有 String 参数的。

根据情况选择编译时异常还是运行时异常：

+ 异常发生频率较高：编译时异常
+ 异常发生频率较低：运行时异常

```java
// 编译时异常
public class MyException extends Exception{
    public MyException(){
        
    }
    public MyException(String s){
        super(s);
    }
}
```

### throw

手动抛出异常。

使用手动抛出异常时，不用 `try catch` 捕捉，因为没有意义（自己创建异常自己捕捉），既然手动抛出异常，那么就应该是想要上级看见，所以使用 `throws` 向上级抛出异常。

```java
public class MyStack{
    int[] s;
    int size;
    int top;
    // ...
    public push(int x) throws Exception{
        if (top >= size) {
            throw new MyStackException("栈已满！");
        }
    }
}
class MyStackException extends Exception{
    public MyStackException(){
        
    }
    public MyStackException(String s){
        super(s);
    } 
}
```

## 九、异常与方法覆盖

重写之后的方法不能比重写之前的方法抛出更多（更宽泛）的异常，可以更少。

子类可以抛出父类方法没有的运行时异常。

```java
class Animal{
	public void doSome(){}
	public void doOther() throws Exception{}
}
class Cat extends Animal{
	// 编译错误：不能抛出更多的异常
	// 错误: Cat中的doSome()无法覆盖Animal中的doSome()
	// public void doSome() throws Exception{}

	// 编译正常，可以抛出更少的异常
	// public void doOther(){}

	// 编译正常，可以抛出更小的异常
	public void doOther() throws IOException{}

	// 编译正常，可以抛出父类方法没有的运行时异常
	public void doSome() throws RuntimeException{}
}
```

